=== tillahoffmann/shedding/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
        "assays": {
            "type": "string",
            "enum": [
                "RdRp_SARSr",
                "ORF1ab",
                "2019-nCoV_N1",
                "PowerChek-E",
                "E_Sarbeco",
                "CCDC-ORF1ab",
                "CCDC-N",
                "HKU-N",
                "S",
                "?"
            ]
        }
    },
    "type": "object",
    "properties": {
        "key": {
            "type": "string",
            "description": "unique identifier for a dataset (typically the same as a publication)"
        },
        "doi": {
            "type": "string",
            "description": "digital object identifier to retrieve the publication or dataste"
        },
        "title": {
            "type": "string",
            "description": "title of the publication"
        },
        "assay": {
            "description": "assay or primer/probe set used to quantify RNA",
            "oneOf": [
                {
                    "$ref": "#/definitions/assays"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/assays"
                    }
                }
            ]
        },
        "loq": {
            "type": [
                "number",
                "null"
            ],
            "description": "level of quantification, i.e. the smallest possible concentration that can be measured, or `null` if not available"
        },
        "patients": {
            "type": "object",
            "properties": {
                "n": {
                    "type": "integer",
                    "description": "number of patients in the study"
                },
                "positive": {
                    "type": "integer",
                    "description": "number of patients with at least one positive stool sample"
                },
                "negative": {
                    "type": "integer",
                    "description": "number of patients without any positive stool samples"
                },
                "details": {
                    "type": "array",
                    "description": "details about individual patients"
                }
            },
            "additionalProperties": false
        },
        "samples": {
            "type": "object",
            "properties": {
                "n": {
                    "type": "integer",
                    "description": "number of samples analysed in the study"
                },
                "positive": {
                    "type": "integer",
                    "description": "number of positive samples"
                },
                "negative": {
                    "type": "integer",
                    "description": "number of negative samples"
                }
            },
            "additionalProperties": false
        },
        "loads": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": [
                            "number",
                            "null"
                        ],
                        "description": "viral load as log10 copies per mL"
                    },
                    "err": {
                        "type": [
                            "number",
                            "null"
                        ],
                        "description": "optional error estimate for the viral load value"
                    },
                    "day": {
                        "type": "integer",
                        "description": "day as reported by the study (often since symptom onset or hospital admission)"
                    },
                    "date": {
                        "type": "string",
                        "description": "specimen collection date"
                    },
                    "patient": {
                        "type": "integer",
                        "description": "zero-based unique patient identifier"
                    },
                    "threshold": {
                        "type": "number",
                        "description": "semi-quantitative qPCR cycle threshold"
                    },
                    "stage": {},
                    "severity": {}
                },
                "required": [
                    "value"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "key",
        "doi",
        "assay",
        "title",
        "patients",
        "samples",
        "loq"
    ]
}

=== tillahoffmann/shedding/publications/Lu2020/Lu2020.json
{
    "$schema": "../../schema.json",
    "assay": "CCDC-N",
    "doi": "10.1101/2020.03.24.20042689",
    "key": "Lu et al. 2020",
    "patients": {
        "n": 15,
        "positive": 11,
        "negative": 4
    },
    "samples": {
        "n": 23,
        "negative": 10,
        "positive": 13
    },
    "loq": 2.1760912591,
    "title": "SARS-CoV-2 detection using digital PCR for COVID-19 diagnosis, treatment monitoring and criteria for discharge",
    "loads": [
        {
            "patient": 1,
            "date": "2020-02-03",
            "value": 2.281033367
        },
        {
            "patient": 2,
            "date": "2020-02-05",
            "value": 2.541579244
        },
        {
            "patient": 4,
            "date": "2020-02-02",
            "value": 2.57634135
        },
        {
            "patient": 4,
            "date": "2020-02-24",
            "value": 2.053078443
        },
        {
            "patient": 6,
            "date": "2020-02-18",
            "value": null
        },
        {
            "patient": 6,
            "date": "2020-02-03",
            "value": 2.51054501
        },
        {
            "patient": 7,
            "date": "2020-02-08",
            "value": 2.278753601
        },
        {
            "patient": 7,
            "date": "2020-02-24",
            "value": null
        },
        {
            "patient": 8,
            "date": "2020-02-21",
            "value": 2.967547976
        },
        {
            "patient": 9,
            "date": "2020-02-14",
            "value": null
        },
        {
            "patient": 9,
            "date": "2020-02-24",
            "value": 1.924279286
        },
        {
            "patient": 10,
            "date": "2020-02-01",
            "value": 2.318063335
        },
        {
            "patient": 10,
            "date": "2020-02-14",
            "value": null
        },
        {
            "patient": 11,
            "date": "2020-02-13",
            "value": 2.025305865
        },
        {
            "patient": 11,
            "date": "2020-02-24",
            "value": null
        },
        {
            "patient": 13,
            "date": "2020-02-12",
            "value": 3.525692525
        },
        {
            "patient": 13,
            "date": "2020-02-24",
            "value": 2.250420002
        },
        {
            "patient": 21,
            "date": "2020-02-13",
            "value": null
        },
        {
            "patient": 22,
            "date": "2020-02-12",
            "value": null
        },
        {
            "patient": 29,
            "date": "2020-02-13",
            "value": null
        },
        {
            "patient": 29,
            "date": "2020-02-24",
            "value": 2.222716471
        },
        {
            "patient": 31,
            "date": "2020-02-18",
            "value": null
        },
        {
            "patient": 36,
            "date": "2020-02-12",
            "value": null
        }
    ]
}

=== tillahoffmann/shedding/publications/Jeong2020/Jeong2020.json
{
    "$schema": "../../schema.json",
    "key": "Jeong et al. 2020",
    "doi": "10.1016/j.cmi.2020.07.020",
    "title": "Viable SARS-CoV-2 in various specimens from COVID-19 patients",
    "patients": {
        "n": 5,
        "positive": 3,
        "negative": 2
    },
    "samples": {
        "n": 5,
        "positive": 3,
        "negative": 2
    },
    "assay": "S",
    "loq": 0.3,
    "loads": [
        {
            "patient": 1,
            "stage": "recovery",
            "value": null,
            "err": null,
            "day": 8
        },
        {
            "patient": 2,
            "stage": "recovery",
            "value": 1.51,
            "err": 0.19,
            "day": 13
        },
        {
            "patient": 3,
            "stage": "recovery",
            "value": null,
            "err": null,
            "day": 11
        },
        {
            "patient": 4,
            "stage": "acute",
            "value": 2.18,
            "err": 0.11,
            "day": 15
        },
        {
            "patient": 5,
            "stage": "recovery",
            "value": 2.01,
            "err": 0.28,
            "day": 30
        }
    ]
}

=== tillahoffmann/shedding/publications/Zheng2020/Zheng2020.json
{
    "$schema": "../../schema.json",
    "key": "Zheng et al. 2020",
    "doi": "10.1136/bmj.m1443",
    "title": "Viral load dynamics and disease severity in patients infected with SARS-CoV-2 in Zhejiang province, China, January-March 2020: retrospective cohort study",
    "patients": {},
    "samples": {
        "n": 842
    },
    "loq": 3,
    "assay": "ORF1ab",
    "loads": [
        {
            "value": 6.680532131835189,
            "severity": "mild"
        },
        {
            "value": 5.906905261607047,
            "severity": "mild"
        },
        {
            "value": 5.744622264028791,
            "severity": "mild"
        },
        {
            "value": 5.267058272707118,
            "severity": "mild"
        },
        {
            "value": 5.010820283143492,
            "severity": "mild"
        },
        {
            "value": 4.9199316047040895,
            "severity": "mild"
        },
        {
            "value": 4.341450198435606,
            "severity": "mild"
        },
        {
            "value": 4.271914154553819,
            "severity": "mild"
        },
        {
            "value": 3.6804811328572953,
            "severity": "mild"
        },
        {
            "value": 3.444718170439998,
            "severity": "mild"
        },
        {
            "value": 3.4099028681966814,
            "severity": "mild"
        },
        {
            "value": 3.375087565953365,
            "severity": "mild"
        },
        {
            "value": 8.088161295600699,
            "severity": "severe"
        },
        {
            "value": 7.711141789199974,
            "severity": "severe"
        },
        {
            "value": 6.990988409773951,
            "severity": "severe"
        },
        {
            "value": 6.574233262241702,
            "severity": "severe"
        },
        {
            "value": 5.304192965965974,
            "severity": "severe"
        },
        {
            "value": 5.2342850545370325,
            "severity": "severe"
        },
        {
            "value": 5.197241734446905,
            "severity": "severe"
        },
        {
            "value": 4.93394994875311,
            "severity": "severe"
        },
        {
            "value": 4.970991143885822,
            "severity": "severe"
        },
        {
            "value": 4.403187648614207,
            "severity": "severe"
        },
        {
            "value": 4.621267777924949,
            "severity": "severe"
        },
        {
            "value": 4.0617261170724035,
            "severity": "severe"
        },
        {
            "value": 3.761391011288481,
            "severity": "severe"
        },
        {
            "value": 3.674958368542697,
            "severity": "severe"
        },
        {
            "value": 4.736481906341794,
            "severity": "severe"
        },
        {
            "value": 4.539011738973063,
            "severity": "severe"
        },
        {
            "value": 4.287974582676071,
            "severity": "severe"
        },
        {
            "value": 3.968886727728499,
            "severity": "severe"
        },
        {
            "value": 3.1255357548875793,
            "severity": "severe"
        },
        {
            "value": 3.2077917938394656,
            "severity": "severe"
        },
        {
            "value": 2.709523279970931,
            "severity": "severe"
        },
        {
            "value": 2.56552979084044,
            "severity": "severe"
        },
        {
            "value": 1.95251251422836,
            "severity": "severe"
        },
        {
            "value": 3.8248921761193024,
            "severity": "severe"
        },
        {
            "value": 3.9920030769383317,
            "severity": "severe"
        },
        {
            "value": 4.325202774061069,
            "severity": "severe"
        },
        {
            "value": 4.740844443909268,
            "severity": "severe"
        },
        {
            "value": 5.102825626703062,
            "severity": "severe"
        },
        {
            "value": 5.234470988310608,
            "severity": "severe"
        },
        {
            "value": 4.8354464854266865,
            "severity": "severe"
        },
        {
            "value": 4.7737100977267914,
            "severity": "severe"
        },
        {
            "value": 4.407552311139096,
            "severity": "severe"
        },
        {
            "value": 4.354075632900855,
            "severity": "severe"
        },
        {
            "value": 3.6669749035446415,
            "severity": "severe"
        },
        {
            "value": 4.086607243413162,
            "severity": "severe"
        },
        {
            "value": 4.004352266939982,
            "severity": "severe"
        },
        {
            "value": 4.798218294041689,
            "severity": "severe"
        },
        {
            "value": 4.452857465648293,
            "severity": "severe"
        }
    ]
}
